---
stages:
  - name: deploy
    # matches tags like ppa-2020-04-14.60fb514_9 where 2020-04-14.60fb514 is build revision from
    # forum and 9 is ppa9 suffix
    if: tag =~ /^ppa-\d{4}-\d{2}-\d{2}.\h{7}_\d+$/  

jobs:
  include:
    - name: Deploy PPA
      stage: deploy
      os: linux
      dist: bionic
      language: python
      python: 3.5
      env:
        - secure: "5l5H2VUpPDAnxngueT2KlE5Yt+SEXNpA2SaitoxuDSVLuoFD2nDcaao7DA20M0JlpDMVQNPdFyB601XRmQGfzq5T4jJlDgcVEGx4sN/9LJ90xVC0YfyE8E+U4UZmUkkjfFPimpxJuoxOl0STX8u/yzzFfSz7VDhFBqKH2we6JJImdHOMw3NpZBzq5dtky8xbjgGs39BkllOVXdHroeT+LqhESa1pB94U3VXz+/FRwjODK2KLzeN3Hdp+Hs2bRCM5ZP5lVWg8hP6ky6ZLk9wY3RfjLhDQUVdbGlbaUw45UdA/3LbINUZuD9K71areY/bAy3Li8V/zPz5OgnPSNxeBsIO7a+pqcxMVcH0NISI/NjoYpUgyN8eGqQzbzQQ5J+oBtbUlJhfSby1q7AZ9t0OlqE9LQuP3bPqAe9IhCFGUtwmRrqMK47UzAXCcZIQ8LqwoHKfbO7g3IOEpoIEpgdoM43U/wZ0sUnVEelqHf1T5MNnKQFuqwTDwhtal2T8IhVJ6x0Zcsa9pCYa9roY50gevOZFbfNsR6BTv6A3aXikrCZxDQ+PkDDn3EEd1KZ7NJtBwTDOIWtj1vTYWZELc7ZuInc9Bi4VrWQv+m6v1tp3O8qJhHgrUXK5GRwywvfxYGY3tf/kWZ9/tUXQiZ9yaAW8iI+J8yOWo1J9y6VnuNkD+Bt0="
      addons:
        apt:
          packages:
            - devscripts
            - dput
            - fakeroot
            - cmake
            - debhelper
            - libalut-dev
            - libboost-all-dev
            - libgl1-mesa-dev
            - libglew-dev
            - libogg-dev
            - libopenal-dev
            - libsdl2-dev
            - libvorbis-dev
      before_script:
        - .ci/before_script.sh
      script:
        - python cmake/make_versioncpp.py . CMake
        - BUILD_REV=$(echo "${TRAVIS_TAG}" | sed -s 's/^ppa-\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\.[0-9a-f]\{7\}\).*/\1/')
        - BUILD_DATE=$(echo "${TRAVIS_TAG}" | sed -s 's/^ppa-\([0-9]\{4\}\)-\([0-9]\{2\}\)-\([0-9]\{2\}\)\.[0-9a-f]\{7\}.*/\1\2\3/')
        - BUILD_PPA=$(echo "${TRAVIS_TAG}" | sed -s 's/^ppa-[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\.[0-9a-f]\{7\}_\([0-9]\+\).*/\1/')
        - echo "REV=${BUILD_REV} DATE=${BUILD_DATE} PPA=${BUILD_PPA}"
        - sed -i "s/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\.[0-9a-f]\{7\}\]/${BUILD_REV}\]/" util/Version.cpp
        # set base debian version before tag
        - sed -i "1,+1{s/bionic\|disco\|eoan\|focal/bionic/g}" debian/changelog
        - tar --xz -cvf ../freeorion_0.4.9.1+1SNAPSHOT${BUILD_DATE}ppa${BUILD_PPA}~bionic.orig.tar.xz --exclude .git --exclude .ci --exclude .github .
        - debuild -S -sa
        - dput ppa:o01eg/freeorion ../freeorion_0.4.9.1+1SNAPSHOT${BUILD_DATE}ppa${BUILD_PPA}~bionic_source.changes
        - sed -i "1,+1{s/bionic\|disco\|eoan\|focal/eoan/g}" debian/changelog
        - tar --xz -cvf ../freeorion_0.4.9.1+1SNAPSHOT${BUILD_DATE}ppa${BUILD_PPA}~eoan.orig.tar.xz --exclude .git --exclude .ci --exclude .github .
        - debuild -S -sa
        - dput ppa:o01eg/freeorion ../freeorion_0.4.9.1+1SNAPSHOT${BUILD_DATE}ppa${BUILD_PPA}~eoan_source.changes
        - sed -i "1,+1{s/bionic\|disco\|eoan\|focal/focal/g}" debian/changelog
        - tar --xz -cvf ../freeorion_0.4.9.1+1SNAPSHOT${BUILD_DATE}ppa${BUILD_PPA}~focal.orig.tar.xz --exclude .git --exclude .ci --exclude .github .
        - debuild -S -sa
        - dput ppa:o01eg/freeorion ../freeorion_0.4.9.1+1SNAPSHOT${BUILD_DATE}ppa${BUILD_PPA}~focal_source.changes

