language: cpp
matrix:
  include:
    - os: linux
      services:
        - docker
      env:
        - BUILD_UNITTEST=true
install:
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      # Download build environment in a docker container
      docker pull freeorion/freeorion-travis-build
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      wget --output-document=FreeOrionSDK.dmg https://github.com/freeorion/freeorion-sdk/releases/download/v7/FreeOrionSDK_7_Clang-MacOSX-10.7-i386.dmg
      hdiutil attach FreeOrionSDK.dmg
      tar -xjf /Volumes/FreeOrionSDK/dep.tar.bz2 -C Xcode
      hdiutil detach /Volumes/FreeOrionSDK
    fi
before_script:
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      git remote -v
      mkdir build
      cd build
      # Add transparent cmake function to allow possible cross platform use of
      # build sections.
      function cmake {
          docker run -v "${TRAVIS_BUILD_DIR}:/freeorion" -w /freeorion/build freeorion/freeorion-travis-build /usr/bin/cmake $@
      }
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      cd Xcode
    fi
script:
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${BUILD_UNITTEST}" == "true" ]]; then
      cmake -DBUILD_HEADLESS=ON -DBUILD_TESTING=ON ..
      cmake --build . -- -j 2 &&
      cmake --build . --target unittest
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      xcodebuild -parallelizeTargets -jobs $(sysctl hw.ncpu | awk '{print $2}') -project FreeOrion.xcodeproj -configuration Release -alltargets
    fi
