from focs._types import (
    _DesignID,
    _Empire,
)

def EmpireShipsDestroyed(empire: _Empire) -> int: ...
def ShipDesignsLost(empire: _Empire) -> int: ...
def ShipDesignsProduced(empire: _Empire) -> int: ...
def ShipDesignsScrapped(empire: _Empire) -> int: ...
def ShipDesignsOwned(empire: _Empire) -> int: ...
def NumPartClassesInShipDesign(design: _DesignID) -> int: ...
def PartOfClassInShipDesign(*, name: str, design: _DesignID) -> int: ...
